name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository under $GITHUB_WORKSPACE.
      uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH.
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup project.
      run: ${{github.workspace}}/Setup.bat

    - name: Build x64 Debug.
      run: msbuild ${{github.workspace}}/HinaEngine.sln /p:Configuration=Debug /p:Platform=x64
      
    - name: Build x64 Release.
      run: msbuild ${{github.workspace}}/HinaEngine.sln /p:Configuration=Release /p:Platform=x64
